[program:pos-queue-comms]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/pos-backend/artisan queue:work database --queue=communications --sleep=3 --tries=3 --backoff=60 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=deploy
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/pos-queue-comms.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=3600
