<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{{ $reportName }}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, sans-serif; font-size: 11px; color: #333; padding: 20px; }
  .header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 16px; display: flex; justify-content: space-between; align-items: flex-start; }
  .store-name { font-size: 16px; font-weight: bold; }
  .report-title { font-size: 14px; font-weight: bold; color: #555; text-align: right; }
  .report-meta { font-size: 9px; color: #888; }
  .summary { display: flex; gap: 16px; margin-bottom: 16px; flex-wrap: wrap; }
  .summary-card { border: 1px solid #ddd; border-radius: 6px; padding: 10px 14px; min-width: 120px; }
  .summary-card .label { font-size: 9px; color: #888; text-transform: uppercase; }
  .summary-card .value { font-size: 16px; font-weight: bold; margin-top: 3px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th { background: #f0f0f0; text-align: left; padding: 6px 8px; border: 1px solid #ddd; font-size: 10px; }
  td { padding: 5px 8px; border: 1px solid #eee; font-size: 10px; }
  tr:nth-child(even) td { background: #f9f9f9; }
  .text-right { text-align: right; }
  tfoot td { background: #f0f0f0; font-weight: bold; }
  .footer { margin-top: 16px; font-size: 9px; color: #aaa; text-align: center; border-top: 1px solid #eee; padding-top: 8px; }
</style>
</head>
<body>
  <div class="header">
    <div>
      <div class="store-name">{{ $store?->name ?? 'Store' }}</div>
      @if($store?->address)<div class="report-meta">{{ $store->address }}</div>@endif
    </div>
    <div>
      <div class="report-title">{{ $reportName }}</div>
      @if(isset($result->meta['date_from']))
      <div class="report-meta">{{ $result->meta['date_from'] }} to {{ $result->meta['date_to'] }}</div>
      @endif
      <div class="report-meta">Generated: {{ now()->format('d M Y H:i') }}</div>
    </div>
  </div>

  {{-- Summary Cards --}}
  @if($result->summary)
  <div class="summary">
    @foreach($result->summary as $card)
    <div class="summary-card">
      <div class="label">{{ $card['label'] }}</div>
      <div class="value">{{ $card['value'] }}</div>
    </div>
    @endforeach
  </div>
  @endif

  {{-- Table --}}
  @if(count($result->rows) > 0)
  <table>
    <thead>
      <tr>
        @foreach($result->columns as $col)
        <th class="{{ ($col['align'] ?? 'left') === 'right' ? 'text-right' : '' }}">
          {{ $col['label'] }}
        </th>
        @endforeach
      </tr>
    </thead>
    <tbody>
      @foreach($result->rows as $row)
      <tr>
        @foreach($result->columns as $col)
        <td class="{{ ($col['align'] ?? 'left') === 'right' ? 'text-right' : '' }}">
          {{ $row[$col['key']] ?? '' }}
        </td>
        @endforeach
      </tr>
      @endforeach
    </tbody>
    @if($result->totals)
    <tfoot>
      <tr>
        @foreach($result->columns as $i => $col)
        <td class="{{ ($col['align'] ?? 'left') === 'right' ? 'text-right' : '' }}">
          @if($i === 0)Total
          @elseif(isset($col['total']) && $col['total'] && isset($result->totals[$col['key']]))
            {{ number_format($result->totals[$col['key']], 2) }}
          @endif
        </td>
        @endforeach
      </tr>
    </tfoot>
    @endif
  </table>
  @endif

  <div class="footer">
    {{ $result->meta['row_count'] ?? 0 }} rows · Report generated by {{ $store?->name ?? 'POS System' }}
  </div>
</body>
</html>
